### ISSUE TITLE
How to make service(init.d) for kongGUI and kongAPIGateway?

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/kong-plugins#2]
I added code in [setup.py](https://github.com/GluuFederation/kong-plugins/blob/master/setup/setup-oxd-kong-plugin.py#L330) for make kongGUI service in init.d but not able to make shell script service file.

Setup.py : https://github.com/GluuFederation/kong-plugins/blob/master/setup/templates/kong-gui
shell script service file: https://github.com/GluuFederation/kong-plugins/blob/master/setup/system/kong-gui

kongGUI run instruction: https://github.com/GluuFederation/kong-plugins/tree/master/kongGUI#run-for-development

Build prototype setup file:  https://repo.gluu.org/ubuntu/pool/main/trusty-devel/gluu-kong-plugins_0.1-2~trusty+Ub14.04_amd64.deb

Same thing we required to do for kongAPIGateway

**Comment by nynymike** [comment]
KongGUI should be installed by the package, not in the `setup.py`. The setup script is used to render configuration, generate data, create keys or certs, gen salt values.... not to do standard linux installation
